services:
  proxy:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./data/ovpn:/data/ovpn
    environment:
      - OVPN_CREDENTIALS=/data/ovpn/credentials
      - INIT_TIMEOUT=8
    ports:
      - 8888:8888
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "8888"]
      timeout: 10s
      start_period: 5s
  proxy-mac:
    build: .
    privileged: true
    volumes:
      - ./data/ovpn:/data/ovpn
    environment:
      - OVPN_CREDENTIALS=/data/ovpn/credentials
      - INIT_TIMEOUT=8
    ports:
      - 8888:8888
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "8888"]
      timeout: 10s
      start_period: 5s
    profiles: [mac]
